apiVersion: 1

datasources:
  - name: Doris
    type: mysql
    access: proxy
    url: doris-fe:9030
    database: thelook_dw
    user: root
    jsonData:
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
    secureJsonData:
      password: ""
    isDefault: true
